# GitHub Labels Configuration
# This file defines all labels for CoderBot integration

# Agent Labels (37 total)
- name: "agent:ai-architect"
  color: "7057ff"
  description: "AI system architecture design"

- name: "agent:ai-engineer"
  color: "7057ff"
  description: "AI/ML implementation"

- name: "agent:api-designer"
  color: "7057ff"
  description: "API design and specification"

- name: "agent:application-architect"
  color: "7057ff"
  description: "Application architecture"

- name: "agent:backend-developer"
  color: "7057ff"
  description: "Backend development"

- name: "agent:cloud-architect"
  color: "7057ff"
  description: "Cloud infrastructure design"

- name: "agent:code-debugger"
  color: "7057ff"
  description: "Debug and fix issues"

- name: "agent:code-documenter"
  color: "7057ff"
  description: "Documentation creation"

- name: "agent:code-refactor"
  color: "7057ff"
  description: "Code refactoring"

- name: "agent:code-reviewer"
  color: "7057ff"
  description: "Code review and quality"

- name: "agent:code-security-auditor"
  color: "7057ff"
  description: "Security audit"

- name: "agent:code-standards-enforcer"
  color: "7057ff"
  description: "Code standards enforcement"

- name: "agent:constraint-innovator"
  color: "7057ff"
  description: "Innovation within constraints"

- name: "agent:data-architect"
  color: "7057ff"
  description: "Data architecture design"

- name: "agent:data-engineer"
  color: "7057ff"
  description: "Data pipeline implementation"

- name: "agent:database-designer"
  color: "7057ff"
  description: "Database schema design"

- name: "agent:devops-engineer"
  color: "7057ff"
  description: "DevOps and CI/CD"

- name: "agent:frontend-developer"
  color: "7057ff"
  description: "Frontend development"

- name: "agent:golang-developer"
  color: "7057ff"
  description: "Go development"

- name: "agent:ideation-synthesizer"
  color: "7057ff"
  description: "Idea synthesis"

- name: "agent:innovation-catalyst"
  color: "7057ff"
  description: "Innovation and creativity"

- name: "agent:ios-developer"
  color: "7057ff"
  description: "iOS development"

- name: "agent:javascript-developer"
  color: "7057ff"
  description: "JavaScript development"

- name: "agent:machine-learning-engineer"
  color: "7057ff"
  description: "ML engineering"

- name: "agent:mobile-developer"
  color: "7057ff"
  description: "Mobile development"

- name: "agent:performance-engineer"
  color: "7057ff"
  description: "Performance optimization"

- name: "agent:project-manager"
  color: "7057ff"
  description: "Project management"

- name: "agent:python-developer"
  color: "7057ff"
  description: "Python development"

- name: "agent:rust-developer"
  color: "7057ff"
  description: "Rust development"

- name: "agent:security-architect"
  color: "7057ff"
  description: "Security architecture"

- name: "agent:security-engineer"
  color: "7057ff"
  description: "Security implementation"

- name: "agent:solution-architect"
  color: "7057ff"
  description: "Solution architecture"

- name: "agent:task-orchestrator"
  color: "7057ff"
  description: "Task orchestration"

- name: "agent:test-automation-engineer"
  color: "7057ff"
  description: "Test automation"

- name: "agent:typescript-developer"
  color: "7057ff"
  description: "TypeScript development"

- name: "agent:ux-designer"
  color: "7057ff"
  description: "UX design"

- name: "agent:wordpress-developer"
  color: "7057ff"
  description: "WordPress development"

# Hierarchy Labels
- name: "epic"
  color: "1d76db"
  description: "Large initiative spanning multiple features"

- name: "story"
  color: "1d76db"
  description: "User story"

- name: "task"
  color: "1d76db"
  description: "Development task"

- name: "subtask"
  color: "1d76db"
  description: "Subtask of a larger task"

# Phase Labels
- name: "phase:1-planning"
  color: "0969da"
  description: "Planning phase"

- name: "phase:2-design"
  color: "0969da"
  description: "Design phase"

- name: "phase:3-implementation"
  color: "0969da"
  description: "Implementation phase"

- name: "phase:4-testing"
  color: "0969da"
  description: "Testing phase"

- name: "phase:5-deployment"
  color: "0969da"
  description: "Deployment phase"

- name: "phase:6-maintenance"
  color: "0969da"
  description: "Maintenance phase"

# Technology Stack Labels
- name: "stack:python"
  color: "0e8a16"
  description: "Python technology"

- name: "stack:nodejs"
  color: "0e8a16"
  description: "Node.js technology"

- name: "stack:react"
  color: "0e8a16"
  description: "React framework"

- name: "stack:postgresql"
  color: "0e8a16"
  description: "PostgreSQL database"

- name: "stack:docker"
  color: "0e8a16"
  description: "Docker containerization"

- name: "stack:kubernetes"
  color: "0e8a16"
  description: "Kubernetes orchestration"

- name: "stack:ai-ml"
  color: "0e8a16"
  description: "AI/ML technology"

# Compliance/Domain Labels
- name: "compliance:hipaa"
  color: "d73a4a"
  description: "HIPAA compliance required"

- name: "compliance:phi"
  color: "d73a4a"
  description: "PHI data handling"

- name: "compliance:gdpr"
  color: "d73a4a"
  description: "GDPR compliance required"

- name: "domain:healthcare"
  color: "d73a4a"
  description: "Healthcare domain"

- name: "domain:financial"
  color: "d73a4a"
  description: "Financial domain"

- name: "domain:analytics"
  color: "d73a4a"
  description: "Analytics domain"

# Size Labels
- name: "size:xs"
  color: "fbca04"
  description: "< 2 hours"

- name: "size:s"
  color: "fbca04"
  description: "2-8 hours"

- name: "size:m"
  color: "fbca04"
  description: "1-3 days"

- name: "size:l"
  color: "fbca04"
  description: "3-5 days"

- name: "size:xl"
  color: "fbca04"
  description: "1-2 weeks"

# Priority Labels
- name: "priority:critical"
  color: "e99695"
  description: "P0 - Critical priority"

- name: "priority:high"
  color: "e99695"
  description: "P1 - High priority"

- name: "priority:medium"
  color: "e99695"
  description: "P2 - Medium priority"

- name: "priority:low"
  color: "e99695"
  description: "P3 - Low priority"

# Special Instruction Labels
- name: "needs:breakdown"
  color: "d4c5f9"
  description: "Needs task breakdown"

- name: "needs:estimation"
  color: "d4c5f9"
  description: "Needs effort estimation"

- name: "needs:architecture"
  color: "d4c5f9"
  description: "Needs architectural design"

- name: "needs:security-review"
  color: "d4c5f9"
  description: "Needs security review"

- name: "auto:execute"
  color: "d4c5f9"
  description: "Auto-execute when labeled"

# Standard Labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

# CoderBot Status Labels
- name: "coderbot"
  color: "0969da"
  description: "Managed by CoderBot AI"

- name: "coderbot:processing"
  color: "fbca04"
  description: "CoderBot is processing"

- name: "coderbot:completed"
  color: "0e8a16"
  description: "CoderBot completed task"

- name: "coderbot:error"
  color: "d73a4a"
  description: "CoderBot encountered an error"